import Navbar from "@/components/navbar/Navbar";
import "./globals.css";
import AuthProviders from "@/providers/AuthProviders";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html data-theme="light" lang="en">
      <body>
        <AuthProviders>
          <Navbar />
          {children}
        </AuthProviders>
      </body>
    </html>
  );
}
